"""initial schema

Revision ID: 2d6dfca413ed
Revises: 
Create Date: 2026-08-28 00:15:23.654182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6dfca413ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('opportunity_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_categories_slug'), ['slug'], unique=True)

    op.create_table('opportunity_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('opportunity_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_tags_slug'), ['slug'], unique=True)

    op.create_table('teacher_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('teacher_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_topics_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('user_type', sa.String(length=30), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('organization_logo_url', sa.String(length=500), nullable=True),
    sa.Column('target_audience', sa.String(length=200), nullable=True),
    sa.Column('eligible_countries', sa.Text(), nullable=True),
    sa.Column('education_level', sa.String(length=150), nullable=True),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('age_requirements', sa.String(length=150), nullable=True),
    sa.Column('other_eligibility', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('funding_type', sa.String(length=60), nullable=True),
    sa.Column('funding_details', sa.Text(), nullable=True),
    sa.Column('application_fee', sa.String(length=100), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('application_opens_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.Column('application_steps', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('source_organization', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('source_checked_at', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('raw_source_data', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['opportunity_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_is_expired'), ['is_expired'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_opportunities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_verification_status'), ['verification_status'], unique=False)

    op.create_table('study_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=230), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['teacher_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_materials_slug'), ['slug'], unique=True)

    op.create_table('teacher_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=True),
    sa.Column('option_b', sa.Text(), nullable=True),
    sa.Column('option_c', sa.Text(), nullable=True),
    sa.Column('option_d', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=150), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['teacher_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_questions_status'), ['status'], unique=False)

    op.create_table('test_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=20), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_exam_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_exam_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['teacher_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('reporter_email', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_tag_map',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['opportunity_tags.id'], ),
    sa.PrimaryKeyConstraint('opportunity_id', 'tag_id')
    )
    op.create_table('reminder_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('reminder_days', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_user_opportunity')
    )
    op.create_table('test_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=10), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['teacher_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_answers')
    op.drop_table('saved_opportunities')
    op.drop_table('reminder_preferences')
    op.drop_table('opportunity_tag_map')
    op.drop_table('opportunity_reports')
    op.drop_table('mock_exam_questions')
    op.drop_table('test_attempts')
    with op.batch_alter_table('teacher_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_questions_status'))

    op.drop_table('teacher_questions')
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_materials_slug'))

    op.drop_table('study_materials')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_verification_status'))
        batch_op.drop_index(batch_op.f('ix_opportunities_status'))
        batch_op.drop_index(batch_op.f('ix_opportunities_slug'))
        batch_op.drop_index(batch_op.f('ix_opportunities_is_expired'))
        batch_op.drop_index(batch_op.f('ix_opportunities_featured'))
        batch_op.drop_index(batch_op.f('ix_opportunities_deadline'))

    op.drop_table('opportunities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teacher_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_topics_slug'))

    op.drop_table('teacher_topics')
    with op.batch_alter_table('opportunity_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_tags_slug'))

    op.drop_table('opportunity_tags')
    with op.batch_alter_table('opportunity_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_categories_slug'))

    op.drop_table('opportunity_categories')
    op.drop_table('mock_exams')
    # ### end Alembic commands ###
